/* oxlint-disable no-restricted-imports */
import { CaretDownIcon, CheckIcon, DesktopIcon, MoonIcon, PersonIcon, SunIcon } from '@radix-ui/react-icons';
import {
  AlertCircle,
  AlertTriangle,
  Archive,
  ArrowDown,
  ArrowDownCircle,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowRightCircle,
  ArrowRightLeft,
  ArrowUp10,
  ArrowUpCircle,
  ArrowUpDown,
  ArrowUpRight,
  BadgeAlert,
  BadgeCheck,
  BellDot,
  BellRing,
  BookOpen,
  Building,
  Building2,
  Calendar,
  CalendarCheck,
  Camera,
  ChartLine,
  ChartNoAxesColumn,
  Check,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleArrowDown,
  CircleCheck,
  CircleCheckBig,
  CircleHelp,
  CirclePause,
  CirclePlay,
  CirclePlus,
  CircleQuestionMark,
  CircleX,
  ClipboardCheck,
  ClipboardPaste,
  Clock,
  Clock2,
  Coins,
  Computer,
  Copy,
  DollarSign,
  Download,
  Edit,
  Ellipsis,
  EllipsisVertical,
  Equal,
  Euro,
  ExternalLink,
  Eye,
  FastForward,
  FileCheck2,
  FileClock,
  FilePlus2,
  Files,
  FileSpreadsheet,
  FileText,
  FileUp,
  FolderSearch,
  FolderUp,
  Fuel,
  Fullscreen,
  Ghost,
  Gift,
  Github,
  Globe,
  Hash,
  HelpCircle,
  Home,
  Hotel,
  Hourglass,
  Info,
  Landmark,
  Layers,
  Laptop2,
  LaptopMinimal,
  Lightbulb,
  Link,
  Link2,
  List,
  ListTodo,
  Loader2,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Mars,
  Maximize2,
  MessageCircleMore,
  MessageSquare,
  Minus,
  MinusCircle,
  MoreHorizontal,
  MoreVertical,
  MoveRight,
  NotepadText,
  OctagonAlert,
  OctagonMinus,
  PanelLeft,
  PartyPopper,
  Pause,
  Pencil,
  Percent,
  Phone,
  Plus,
  PlusCircle,
  PoundSterling,
  RefreshCcw,
  RefreshCw,
  Repeat,
  RotateCcw,
  Save,
  Scale,
  ScanEye,
  ScanLine,
  ScanSearch,
  Search,
  Send,
  Settings,
  Settings2,
  ShieldCheck,
  ShoppingCart,
  SlidersVertical,
  Smartphone,
  Sparkle,
  SquarePen,
  SquarePlus,
  SwissFrancIcon,
  Tag,
  Target,
  Timer,
  TimerReset,
  Trash2,
  Trophy,
  Undo2,
  Upload,
  User,
  UserMinus,
  UserPen,
  UserPlus,
  UserRoundCheck,
  UserRoundPlus,
  Users,
  Venus,
  Video,
  Wallet,
  X,
  Zap,
} from 'lucide-react';
import BrandBg from './brand-bg.js';
import CheckMark from './check-mark.js';
import { ArrowLeftRightCircle } from './icons/ArrowLeftRightCircle.js';
import { ArrowUpRightCircle } from './icons/ArrowUpRightCircle.js';
import { FileTextCentered } from './icons/FileTextCentered.js';
import { PartyPopperGradient } from './icons/PartyPopperGradient.js';
import Spinner from './spinner.js';

export const Icon = {
  AlertCircle,
  AlertTriangle,
  Archive,
  ArrowDown,
  ArrowDownCircle,
  ArrowLeft,
  ArrowLeftRight,
  ArrowLeftRightCircle,
  ArrowRight,
  ArrowRightCircle,
  ArrowRightLeft,
  ArrowUp10,
  ArrowUpCircle,
  ArrowUpDown,
  ArrowUpRightCircle,
  ArrowUpRight,
  BadgeAlert,
  BadgeCheck,
  BellDot,
  BellRing,
  BookOpen,
  BrandBg,
  Building,
  Building2,
  Calendar,
  CalendarCheck,
  Camera,
  CaretDown: CaretDownIcon,
  ChartLine,
  ChartNoAxesColumn,
  Check: CheckIcon,
  Check2: CheckMark,
  CheckCircle,
  CheckCircle2,
  CheckLucide: Check,
  ChevronDown,
  Coins,
  Computer,
  ChevronLeft,
  ChevronRight,
  ChevronsUpDown,
  ChevronUp,
  Circle,
  CircleAlert,
  CircleArrowDown,
  CircleCheck,
  CircleCheckBig,
  CircleHelp,
  CirclePause,
  CirclePlay,
  CirclePlus,
  CircleQuestionMark,
  CircleX,
  ClipboardCheck,
  ClipboardPaste,
  Clock: Clock2,
  ClockLucide: Clock,
  Copy,
  CopyIcon: Copy,
  Desktop: DesktopIcon,
  Dollar: DollarSign,
  Download,
  Edit,
  Ellipsis,
  EllipsisVertical,
  Equal,
  Euro,
  ExternalLink,
  Eye,
  FastForward,
  FileCheck: FileCheck2,
  FileClock,
  Files,
  FilePlus2,
  FileSpreadsheet,
  FileText,
  FileTextCentered,
  FileUp,
  FolderSearch,
  FolderUp,
  Fuel,
  Fullscreen,
  Ghost,
  Gift,
  Github,
  Globe,
  Hash,
  Help: HelpCircle,
  Home,
  Hotel,
  Hourglass,
  Individual: User,
  Info,
  Landmark,
  Layers,
  Laptop: Laptop2,
  LaptopMinimal,
  LegalEntity: Building2,
  Lightbulb,
  Link,
  Link2,
  List,
  ListTodo,
  Loader: Loader2,
  Lock,
  LogOut,
  Mail,
  MapPin,
  Mars,
  Maximize2,
  MessageCircleMore,
  MessageSquare,
  Minus,
  MinusCircle,
  Moon: MoonIcon,
  MoreHorizontal,
  MoreVertical,
  MoveRight,
  NotepadText,
  OctagonAlert,
  OctagonMinus,
  PanelLeft,
  PartyPopper,
  PartyPopperGradient,
  Pause,
  Pencil,
  Percent,
  Person: PersonIcon,
  Phone,
  Plus,
  PlusCircle,
  PoundSterling,
  RefreshCw,
  Repeat,
  RotateCcw,
  Save,
  Scale,
  ScanEye,
  ScanLine,
  ScanSearch,
  Search,
  Send,
  Settings,
  Settings2,
  ShieldCheck,
  ShoppingCart,
  SlidersVertical,
  Smartphone,
  Sparkle,
  Spinner,
  SquarePen,
  SquarePlus,
  Sun: SunIcon,
  Tag,
  Target,
  Timer,
  TimerReset,
  Trash2,
  Trophy,
  Upload,
  Undo2,
  User,
  Users,
  UserMinus,
  UserPen,
  UserPlus,
  UserRoundCheck,
  UserRoundPlus,
  Venus,
  Video,
  Wallet,
  X,
  Zap,
  Refresh: RefreshCcw,
  SwissFranc: SwissFrancIcon,
};

export * from './BankLogo.js';
export * from './Flag.js';
export * from './flags/EULogo.js';
export * from './flags/UKLogo.js';
export * from './flags/USALogo.js';
export * from './Logo.js';
export * from './NetworkIcon.js';
export * from './partners/AmundiLogo.js';
export * from './partners/BnpLogo.js';
export * from './partners/CaceisLogo.js';
export * from './partners/CMEGroupLogo.js';
export * from './partners/CreditAgricoleLogo.js';
export * from './partners/MarexLogo.js';
export * from './partners/MsciLogo.js';
export * from './partners/PwcLogo.js';
export * from './Porcupine.js';
export * from './RialtoNetworkIcon.js';
export * from './StableCoinIcon.js';
export * from './TokenLogo.js';
